- hosts: all
  gather_facts: false
  tasks:
    - name: Apt update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      become: yes

    - name: Forward traffic
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      become: yes

    - name: Get default interface
      shell: ip route | grep default | awk '{print $5}'
      register: default_interface

    - name: Get local ip
      shell: ip -f inet a l {{ default_interface.stdout }} | awk '/inet/ {print $2}' | cut -d/ -f1
      register: local_ip

    - name: Configure iptables rules
      template:
        src: ../configs/rules.v4.j2
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Apply iptables rules
      shell: iptables-restore < /etc/iptables/rules.v4
      become: yes

    - name: Add the ip_gre module
      shell: modprobe ip_gre
      become: yes

    - name: Copy gre tunnel netplan
      template:
        src: ../configs/90-gre-tunnel.yaml.j2
        dest: /etc/netplan/90-gre-tunnel.yaml
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Gre tunnel keepalive
      cron:
        name: "gre tunnel keepalive"
        minute: "*"
        hour: "*"
        job: "/usr/bin/ping -c 10 -i 5 {{ gre_local_peer }} >/dev/null 2>&1"
